export const SET_LOADING = 'SET_LOADING';
export const GET_TODO_ITEMS_SUCCESS = 'GET_TODO_ITEMS_SUCCESS';
export const CREATE_TODO_ITEM_SUCCESS = 'CREATE_TODO_ITEM';
export const EDIT_TODO_ITEM_SUCCESS = 'EDIT_TODO_ITEM_SUCCESS';
export const DELETE_TODO_ITEM_SUCCESS = 'DELETE_TODO_ITEM_SUCCESS';


export const ADD_TODO_ACTION = 'ADD_TODO_ACTION';
export const DELETE_TODO_ACTION = 'DELETE_TODO_ACTION';
export const EDIT_TODO_ACTION = 'EDIT_TODO_ACTION';
