export const SET_LOADING='SET_LOADING';
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR="REGISTER_USER_ERROR";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR="LOGIN_USER_ERROR";
export const LOGOUT_USER="LOGOUT_USER";
export const GET_TODO_ITEMS_SUCCESS='GET_TODO_ITEMS_SUCCESS';
export const GET_TODO_ITEMS_ERROR="GET_TODO_ITEMS_ERROR"
export const CREATE_TODO_ITEM_SUCCESS="CREATE_TODO_ITEM";
export const CREATE_TODO_ITEM_ERROR="CREATE_TODO_ITEM_ERROR";
export const EDIT_TODO_ITEM_SUCCESS="EDIT_TODO_ITEM_SUCCESS";
export const EDIT_TODO_ITEM_ERROR="EDIT_TODO_ITEM_ERROR";
export const DELETE_TODO_ITEM_SUCCESS="DELETE_TODO_ITEM_SUCCESS";
export const DELETE_TODO_ITEM_ERROR="DELETE_TODO_ITEM_ERROR";
export const SET_USER="SET_USER";
export const SWITCH_EDIT_MODE="SWITCH_EDIT_MODE";

